/*
 * Copyright (C) 2010  PDOK
 *
 * This file is part of Geozet
 *
 * Geozet is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Geozet is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Geozet.  If not, see <http://www.gnu.org/licenses/>.
 */

Ext.namespace('Geozet','Geozet.Strategy','Geozet.Renderer','Geozet.plugins','Geozet.widgets','Geozet.Format','Geozet.Control');Geozet.Viewer=function(){var map;var legend;var popup;var vlakgericht;var vectorLayer;var selectfeature;var search;var panzoombar;var resizemap;return{create:function(config){this.config=config;$(window).unload(function(){Geozet.Viewer.destroy();});OpenLayers.Lang.setCode('nl');OpenLayers.Number.decimalSeparator=",";this.createMap();this.createPopup();this.createVlakgericht();this.createOverviewMap();this.createBaseLayer();this.createVectorLayers();this.createSelectFeatureControl();this.createSearch();this.createLegendPanel();var searchCb=function(req){var returnObj=search.handleResponse(req,true);this.createMapPanel(returnObj.center,returnObj.zoom);};var cb=OpenLayers.Function.bind(searchCb,this);var startHash=document.location.hash;if(startHash!=""&&startHash!="#"){search.setSearchForm("geozetCoreEntree");search.sendRequestFromHash(startHash,cb);}else{this.createMapPanel();}
this.createPanZoomBar();},createLegendPanel:function(visibleClasses){if(Ext.get(this.config.legendDiv)){legend=new Geozet.Legend({map:map,ulCls:this.config.legendUlCls,renderTo:this.config.legendDiv,visibleClasses:visibleClasses,legendConfig:this.config.classificationInfo});}},createPanZoomBar:function(){if(Ext.get(this.config.panZoomBarDiv)){var options=Geozet.config.panZoomBarOptions;options.map=map;options.renderTo=Geozet.config.panZoomBarDiv;panzoombar=new Geozet.PanZoomBar(options);}},createMapPanel:function(center,zoom){resizemap=new Geozet.plugins.ResizeMap({hidden:!Geozet.config.containers.resizeMap,staticSize:this.config.staticMapSize,autoWidth:this.config.mapAutoWidth,autoHeight:this.config.mapAutoHeight});var options=OpenLayers.Util.extend({map:map,border:false,header:false,renderTo:this.config.mapDiv,width:(this.config.mapAutoWidth===true)?undefined:this.config.staticMapSize[0],height:(this.config.mapAutoHeight===true)?undefined:this.config.staticMapSize[1],plugins:[resizemap]},this.config.mapPanel);if(center){options.center=center;}
if(zoom){options.zoom=zoom;}
mapPanel=new GeoExt.MapPanel(options);},createSelectFeatureControl:function(){var mouseOver=function(feature){var viewport=Ext.get(map.viewPortDiv);if(!viewport.hasClass('olDragDown')&&!viewport.hasClass('olDrawBox')){popup.openPopoverFor(feature);}};var mouseOut=function(feature){popup.hidePopover();};var mouseClick=function(feature){popup.openPopupFor(feature);return false;};var callbacks={"over":mouseOver,"out":mouseOut,"click":mouseClick};selectfeature=new OpenLayers.Control.SelectFeature(vectorLayer,{hover:true,autoActivate:true,callbacks:callbacks});map.addControl(selectfeature);},createVectorLayers:function(){vectorLayer=new OpenLayers.Layer.Vector(null,this.config.bekendmakingenLayer);map.addLayer(vectorLayer);var keys=['provincie','gemeente','wijk'];for(var i=0;i<keys.length;i++){var options=this.config.clusterLayer[keys[i]];var lyr=new OpenLayers.Layer.Vector(options.title,options);map.addLayer(lyr);}},createBaseLayer:function(){map.addLayer(this.config.backgroundLayer);},createPopup:function(){popup=new Geozet.Popup({map:map,iconSize:this.config.iconSize,clusterZoom:this.config.clusterZoom,attributes:this.config.popupAttributes,templates:this.config.templates});},createVlakgericht:function(){vlakgericht=new Geozet.Vlakgericht({map:map});},createOverviewMap:function(){var div=Ext.get(this.config.overviewDiv);if(div){this.config.overview.div=div.dom;var overview=new OpenLayers.Control.OverviewMap(this.config.overview);map.addControl(overview);}},createSearch:function(){search=new Geozet.Search(this.config,map);},createMap:function(){map=new OpenLayers.Map(this.config.mapDiv,this.config.map);var options=Geozet.config.scaleBar;options.div=Ext.get(options.id).dom;if(options.div){map.addControl(new Geozet.Control.ScaleBar(options));}
if(Geozet.config.attributionDiv){map.addControl(new OpenLayers.Control.Attribution({div:Ext.get(Geozet.config.attributionDiv).dom}));}
map.events.register("zoomend",this,this.attachLayerToControl);},destroy:function(){if(map&&map.events){map.events.unregister("zoomend",this,this.attachLayerToControl);}
if(popup){popup.destroy();popup=null;}
if(vlakgericht){vlakgericht.destroy();vlakgericht=null;}
if(legend){legend.destroy();legend=null;}
if(panzoombar){panzoombar.destroy();panzoombar=null;}
if(search){search.destroy();search=null;}
if(resizemap){resizemap.destroy();resizemap=null;}
if(mapPanel){mapPanel.destroy();mapPanel=null;}
if(map){map.destroy();map=null;}},attachLayerToControl:function(){for(var i=0,len=map.layers.length;i<len;i++){var layer=map.layers[i];if(layer instanceof OpenLayers.Layer.Vector&&layer.inRange){selectfeature.setLayer(layer);break;}}},getPopup:function(){return popup;},getMap:function(){return map;},getLegend:function(){return legend;}};}();Geozet.VERSION_NUMBER="1.1";Geozet.Format.XLSLUS=OpenLayers.Class(OpenLayers.Format.XML,{defaultVersion:"1.1.0",version:null,parser:null,initialize:function(options){OpenLayers.Format.XML.prototype.initialize.apply(this,[options]);},writeGeocodeRequest:function(address,options){var version=(options&&options.version)||this.version||this.defaultVersion;if(!this.parser||this.parser.VERSION!=version){var format=Geozet.Format.XLSLUS["v"+version.replace(/\./g,"_")];if(!format){throw"Can't find a XLSLUS parser for version "+
version;}
this.parser=new format(options);}
var root=this.parser.writeGeocodeRequest(address);return OpenLayers.Format.XML.prototype.write.apply(this,[root]);},writeReverseGeocodeRequest:function(position,options){var version=(options&&options.version)||this.version||this.defaultVersion;if(!this.parser||this.parser.VERSION!=version){var format=Geozet.Format.XLSLUS["v"+version.replace(/\./g,"_")];if(!format){throw"Can't find a XLSLUS parser for version "+
version;}
this.parser=new format(options);}
var root=this.parser.writeReverseGeocodeRequest(position);return OpenLayers.Format.XML.prototype.write.apply(this,[root]);},read:function(data,options){if(typeof data=="string"){data=OpenLayers.Format.XML.prototype.read.apply(this,[data]);}
var root=data.documentElement;var version=this.version;if(!version){version=root.getAttribute("version");if(!version){version=this.defaultVersion;}}
if(!this.parser||this.parser.VERSION!=version){var format=Geozet.Format.XLSLUS["v"+version.replace(/\./g,"_")];if(!format){throw"Can't find a XLSLUS parser for version "+
version;}
this.parser=new format(options);}
var xlslus=this.parser.read(data);return xlslus;},CLASS_NAME:"Geozet.Format.XLSLUS"});Geozet.Strategy.Sort=OpenLayers.Class(OpenLayers.Strategy,{sortHeight:25,sortWidth:15,initialize:function(options){OpenLayers.Strategy.prototype.initialize.apply(this,[options]);},activate:function(){this.layer.events.on({"beforefeaturesadded":this.sort,scope:this});},deactivate:function(){this.layer.events.un({"beforefeaturesadded":this.sort,scope:this});},sort:function(evt){var features=evt.features;var map=this.layer.map;var bounds=map.getExtent();var sortHeight=(this.sortHeight/map.getSize().h)*bounds.getHeight();var sortWidth=(this.sortWidth/map.getSize().w)*bounds.getWidth();var sort=[];var outOfMap=[];for(var i=0,len=features.length;i<len;i++){var feature=features[i];var distX=feature.geometry.x-bounds.left;var distY=bounds.top-feature.geometry.y;var idx=Math.ceil(distY/sortHeight)-1;var idx_col=Math.ceil(distX/sortWidth)-1;if(idx_col<0||idx<0){outOfMap.push(feature);}else{if(!sort[idx]){sort[idx]=[];}
if(!sort[idx][idx_col]){sort[idx][idx_col]=[];}
sort[idx][idx_col].push(feature);}}
var result=[];var printId=0;for(var i=0,len=sort.length;i<len;i++){var row=sort[i];if(row){for(var j=0,lenj=row.length;j<lenj;j++){if(row[j]){for(var k=0,lenk=row[j].length;k<lenk;k++){printId++;row[j][k].attributes.printid=printId;result.push(row[j][k]);}}}}}
for(var i=0,len=outOfMap.length;i<len;i++){printId++;outOfMap[i].attributes.printid=printId;}
evt.features=result.concat(outOfMap);},CLASS_NAME:"Geozet.Strategy.Sort"});Geozet.Strategy.ThemeVisibility=OpenLayers.Class(OpenLayers.Strategy,{attributeName:null,initialize:function(options){OpenLayers.Strategy.prototype.initialize.apply(this,[options]);},activate:function(){this.layer.events.on({"beforefeaturesadded":this.updateVisibility,scope:this});},deactivate:function(){this.layer.events.un({"beforefeaturesadded":this.updateVisibility,scope:this});},getFilterState:function(){if(Geozet.Viewer.getLegend()){return Geozet.Viewer.getLegend().getState();}},updateVisibility:function(evt){var features=evt.features;var state=this.getFilterState();for(var i=0,len=features.length;i<len;i++){var feature=features[i];var cls=feature.attributes[this.attributeName];if(state[cls]===false){feature.style={display:"none"};}}},CLASS_NAME:"Geozet.Strategy.ThemeVisibility"});Geozet.Control.ScaleBar=OpenLayers.Class(OpenLayers.Control.ScaleBar,{initialize:function(options){OpenLayers.Control.prototype.initialize.apply(this,[options]);if(!document.styleSheets){this.limitedStyle=true;}
if(this.limitedStyle){this.appliedStyles=OpenLayers.Util.extend({},this.defaultStyles);OpenLayers.Util.extend(this.appliedStyles,this.customStyles);}
this.element=document.createElement('div');this.element.style.position='relative';this.element.className=this.displayClass+'Wrapper';this.labelContainer=document.createElement('div');this.labelContainer.className=this.displayClass+'Units';this.labelContainer.style.position='absolute';this.graphicsContainer=document.createElement('div');this.graphicsContainer.style.position='absolute';this.graphicsContainer.className=this.displayClass+'Graphics';this.numbersContainer=document.createElement('div');this.numbersContainer.style.position='absolute';this.numbersContainer.className=this.displayClass+'Numbers';this.element.appendChild(this.numbersContainer);this.element.appendChild(this.graphicsContainer);},draw:function(){OpenLayers.Control.prototype.draw.apply(this,arguments);this.dxMarkerMajor=(this.styleValue('MarkerMajor','borderLeftWidth')+
this.styleValue('MarkerMajor','width')+
this.styleValue('MarkerMajor','borderRightWidth'))/2;this.dxMarkerMinor=(this.styleValue('MarkerMinor','borderLeftWidth')+
this.styleValue('MarkerMinor','width')+
this.styleValue('MarkerMinor','borderRightWidth'))/2;this.dxBar=(this.styleValue('Bar','borderLeftWidth')+
this.styleValue('Bar','borderRightWidth'))/2;this.dxBarAlt=(this.styleValue('BarAlt','borderLeftWidth')+
this.styleValue('BarAlt','borderRightWidth'))/2;this.dxNumbersBox=this.styleValue('NumbersBox','width')/2;var classNames=['Bar','BarAlt','MarkerMajor','MarkerMinor'];if(this.singleLine){classNames.push('LabelBoxSingleLine');}else{classNames.push('NumbersBox','LabelBox');}
var vertDisp=0;for(var classIndex=0;classIndex<classNames.length;++classIndex){var cls=classNames[classIndex];vertDisp=Math.max(vertDisp,2+this.styleValue(cls,'top')+this.styleValue(cls,'height'));}
this.element.style.height=vertDisp+'px';this.xOffsetSingleLine=this.styleValue('LabelBoxSingleLine','width')+
this.styleValue('LabelBoxSingleLine','left');this.div.appendChild(this.element);this.map.events.register('moveend',this,this.onMoveend);this.update();return this.div;},update:function(scale){if(this.map.baseLayer==null||!this.map.getScale()){return;}
this.scale=(scale!=undefined)?scale:this.map.getScale();this.element.style.width=this.maxWidth+'px';var comp=this.getComp();this.setSubProps(comp);this.labelContainer.innerHTML="";this.graphicsContainer.innerHTML="";this.numbersContainer.innerHTML="";var numDiv=this.divisions*this.subdivisions;var alignmentOffset={left:0+(this.singleLine?0:this.dxNumbersBox),center:(this.maxWidth/2)-
(numDiv*this.subProps.pixels/2)-
(this.singleLine?this.xOffsetSingleLine/2:0),right:this.maxWidth-
(numDiv*this.subProps.pixels)-
(this.singleLine?this.xOffsetSingleLine:this.dxNumbersBox)}
var xPos,measure,divNum,cls,left;for(var di=0;di<this.divisions;++di){xPos=di*this.subdivisions*this.subProps.pixels+
alignmentOffset[this.align];this.graphicsContainer.appendChild(this.createElement("MarkerMajor"," ",xPos-this.dxMarkerMajor));if(!this.singleLine){measure=(di==0)?0:OpenLayers.Number.format((di*this.subdivisions)*this.subProps.length,this.subProps.dec,this.thousandsSeparator);this.numbersContainer.appendChild(this.createElement("NumbersBox",measure,xPos-this.dxNumbersBox));}
for(var si=0;si<this.subdivisions;++si){if((si%2)==0){cls="Bar";left=xPos-this.dxBar;}else{cls="BarAlt";left=xPos-this.dxBarAlt;}
this.graphicsContainer.appendChild(this.createElement(cls," ",left,this.subProps.pixels));if(si<this.subdivisions-1){divNum=(di*this.subdivisions)+si+1;xPos=divNum*this.subProps.pixels+
alignmentOffset[this.align];this.graphicsContainer.appendChild(this.createElement("MarkerMinor"," ",xPos-this.dxMarkerMinor));if(this.showMinorMeasures&&!this.singleLine){measure=divNum*this.subProps.length;this.numbersContainer.appendChild(this.createElement("NumbersBox",measure,xPos-this.dxNumbersBox));}}}}
xPos=numDiv*this.subProps.pixels;xPos+=alignmentOffset[this.align];this.graphicsContainer.appendChild(this.createElement("MarkerMajor"," ",xPos-this.dxMarkerMajor));measure=OpenLayers.Number.format(numDiv*this.subProps.length,this.subProps.dec,this.thousandsSeparator);if(!this.singleLine){this.numbersContainer.appendChild(this.createElement("NumbersBox",measure+' '+this.subProps.abbr,xPos-this.dxNumbersBox));}
var labelBox=document.createElement('div');labelBox.style.position='absolute';var labelText;if(this.singleLine){labelText=measure;labelBox.className=this.displayClass+'LabelBoxSingleLine';labelBox.style.left=Math.round(xPos+this.styleValue('LabelBoxSingleLine','left'))+'px';}else{labelText='';labelBox.className=this.displayClass+'LabelBox';labelBox.style.textAlign='center';labelBox.style.width=Math.round(numDiv*this.subProps.pixels)+'px'
labelBox.style.left=Math.round(alignmentOffset[this.align])+'px';labelBox.style.overflow='hidden';}
if(this.abbreviateLabel){labelText+=' '+this.subProps.abbr;}else{labelText+=' '+this.subProps.units;}
labelBox.appendChild(document.createTextNode(labelText));this.labelContainer.appendChild(labelBox);},CLASS_NAME:"Geozet.Control.ScaleBar"});Geozet.PanZoomBar=Ext.extend(Ext.BoxComponent,{renderTo:null,slideFactor:50,slideRatio:null,onRender:function(){Geozet.PanZoomBar.superclass.onRender.apply(this,arguments);this.el=Ext.get(this.renderTo);var ul=Ext.DomHelper.append(this.el,{tag:'ul'});var zoombar=Ext.DomHelper.append(this.el,{tag:'div','class':'zoombar'});var options=this.sliderOptions||{};options.renderTo=zoombar;options.map=this.map;this.slider=new GeoExt.ZoomSlider(options);this.createButton(ul,'panup','up',OpenLayers.i18n("panUpTitle"));this.createButton(ul,'panleft','left',OpenLayers.i18n("panLeftTitle"));this.createButton(ul,'panright','right',OpenLayers.i18n("panRightTitle"));this.createButton(ul,'pandown','down',OpenLayers.i18n("panDownTitle"));this.createButton(ul,'zoomin','zoom-plus',OpenLayers.i18n("zoominTitle"));this.createButton(ul,'zoomout','zoom-min',OpenLayers.i18n("zoomoutTitle"));Ext.get(this.el).on('click',this.clickButton,this,{delegate:'a'});},destroy:function(){Ext.get(this.el).un('click',this.clickButton,this,{delegate:'a'});this.slider.destroy();this.slider=null;this.map=null;Geozet.PanZoomBar.superclass.destroy.apply(this,arguments);},getSlideFactor:function(dim){if(!this.slideRatio){var slideFactorPixels=this.slideFactor;return slideFactorPixels;}else{var slideRatio=this.slideRatio;return this.map.getSize()[dim]*slideRatio;}},clickButton:function(evt){switch(Ext.get(evt.target).id){case"panup":this.map.pan(0,-this.getSlideFactor("h"));break;case"pandown":this.map.pan(0,this.getSlideFactor("h"));break;case"panleft":this.map.pan(-this.getSlideFactor("w"),0);break;case"panright":this.map.pan(this.getSlideFactor("w"),0);break;case"zoomin":this.map.zoomIn();break;case"zoomout":this.map.zoomOut();break;default:break;}
evt.stopEvent();},createButton:function(parent,id,cls,title){var li=Ext.DomHelper.append(parent,{tag:'li',cls:cls});var anchor=Ext.DomHelper.append(li,{tag:'a',id:id,href:'#',html:title,title:title});}});Geozet.Popup=OpenLayers.Class({map:null,attributes:null,templates:null,clusterZoom:null,iconSize:null,layer:null,popuppedFeature:null,feature:null,popupDiv:null,popoverDiv:null,itemLength:0,itemCurrent:1,initialize:function(options){OpenLayers.Util.extend(this,options);var closeClick=OpenLayers.Function.bind(this.hidePopup,this);$('body').delegate('#geozetPopup .close','click',closeClick);this.popupDiv=Ext.DomHelper.append(Ext.getBody(),{tag:'div',id:'geozetPopup'});this.popoverDiv=Ext.DomHelper.append(Ext.getBody(),{tag:'div',id:'geozetPopover'});Ext.get(this.popoverDiv).on('click',this.onPopoverClick,this);this.map.events.register('move',this,this.move);$('body').delegate('#geozetPopupForward','click',function(){Geozet.Viewer.getPopup().go(true);return false;});$('body').delegate('#geozetPopupBack','click',function(){Geozet.Viewer.getPopup().go(false);return false;});},getFeatureType:function(feature){if(!feature.cluster&&feature.attributes[this.attributes.categorie]||(feature.cluster&&feature.attributes[this.attributes.count]===1)){return"feature";}else if(!feature.cluster){return"serversidecluster";}else{return"cluster";}},getTitleForFeature:function(feature){var templateKey=this.getFeatureType(feature)+"PopoverText";if(feature.layer&&feature.layer.name){feature.attributes.layername=feature.layer.name;}
return this.templates[templateKey].applyTemplate(feature.attributes);},openPopoverFor:function(feature){if(feature==this.popuppedFeature){return;}
this.feature=feature;if(feature.layer){this.layer=feature.layer;}
var featurePos=this.featurePosOfPoint(feature);if(featurePos!==null){var templateKey=this.getFeatureType(feature)+"Popover";if(feature.layer&&feature.layer.name){feature.attributes.layername=feature.layer.name;}
this.templates[templateKey].overwrite(Ext.get('geozetPopover'),feature.attributes);var categorie=feature.attributes[this.attributes.categorie]||"cluster";$('#geozetPopover span').removeClass().addClass(categorie);$('#geozetPopover').css({'display':'block','top':featurePos.top,'left':featurePos.left});}},removeActiveState:function(){if(this.popuppedFeature){delete this.popuppedFeature.attributes.active;var layer=this.popuppedFeature.layer;if(layer){layer.drawFeature(this.popuppedFeature);}}},addActiveState:function(){if(this.popuppedFeature){this.popuppedFeature.attributes.active=true;var layer=this.popuppedFeature.layer;if(layer){layer.drawFeature(this.popuppedFeature);}}},openPopupFor:function(feature){this.removeActiveState();this.map=feature.layer.map;this.hidePopover();this.feature=feature;if(feature.layer){this.layer=feature.layer;}
this.popuppedFeature=feature;this.addActiveState();if(!feature.attributes[this.attributes.categorie]){var center=new OpenLayers.LonLat(this.feature.geometry.x,this.feature.geometry.y);this.map.setCenter(center,this.clusterZoom[this.feature.attributes.cluster]);return;}
var ft=this.getFeatureType(feature);if(ft==="feature"){this.templates["featurePopupHeader"].overwrite(Ext.get('geozetPopup'),feature.attributes);this.templates["featurePopupContent"].append(Ext.get('geozetPopup'),feature.attributes);}
if(ft==="cluster"){this.itemLength=feature.attributes[this.attributes.count];var html=this.templates["clusterPopupHeader"].applyTemplate(feature.attributes);var first=true;for(var i=0;i<feature.cluster.length;i++){var child=feature.cluster[i];if(!(child.style&&'none'==child.style.display)){child.attributes.activeClass=(first===true)?"active":"";first=false;html+=this.templates['clusterChildPopupHeader'].applyTemplate(child.attributes);html+=this.templates['featurePopupContent'].applyTemplate(child.attributes);html+=this.templates['clusterChildPopupFooter'].applyTemplate();}}
html+=this.templates["clusterPopupFooter"].applyTemplate(feature.attributes);Ext.get("geozetPopup").update(html);}
$('#geozetPopup .close').focus();this.move();},go:function(next){var to=next?this.itemCurrent+1:this.itemCurrent-1;if((to>0)&&(to<=this.itemLength)){this.itemCurrent=to;$('#geozetPopup ul.cluster li').removeClass('active');$('#geozetPopup p.btn a').removeClass().attr('disabled','');$('#geozetPopup p.btn span').html(this.itemCurrent);$('#geozetPopup ul.cluster li:nth-child('+this.itemCurrent+')').addClass('active');if(this.itemCurrent==this.itemLength){$('#geozetPopupForward').addClass('inactive').attr('disabled','disabled');}
if(this.itemCurrent==1){$('#geozetPopupBack').addClass('inactive').attr('disabled','disabled');}}
this.move();return false;},onPopoverClick:function(){this.openPopupFor(this.feature);},hidePopover:function(){$('#geozetPopover').css('display','none');},hidePopup:function(evt,soft){if(document.getElementById('geozetPopup')){$('#geozetPopup').css('left','-999999px');}
if(!soft){Ext.get('geozetPopup').update('');if(this.popuppedFeature){var featureElement=Ext.get(this.popuppedFeature.id);if(featureElement){featureElement.focus();}}
this.removeActiveState();this.popuppedFeature=null;this.itemLength=0;this.itemCurrent=1;}
return false;},move:function(){this.hidePopover();if(this.popuppedFeature){if(!this.popuppedFeature.layer){var features=this.layer.features;var x=this.popuppedFeature.geometry.x;var y=this.popuppedFeature.geometry.y;var newPopuppedFeature=null;for(var i=0;i<features.length;i++){if(x==features[i].geometry.x&&y==features[i].geometry.y){newPopuppedFeature=features[i];}}
this.hidePopup();if(newPopuppedFeature){this.popuppedFeature=newPopuppedFeature;this.openPopupFor(this.popuppedFeature);}}else{var featurePos=this.featurePosOfPoint(this.popuppedFeature);if((!this.popuppedFeature.onScreen(true)||(featurePos===null))||!this.popuppedFeature.layer.calculateInRange())
{this.hidePopup(null,true);}else{var height=$('#geozetPopup').height();if(height>20){var left=featurePos.left-10;var top=featurePos.top-height-20;$('#geozetPopup').css({'top':top,'left':left});}}}}},featurePosOfPoint:function(feature){if(feature.geometry!=null){var lonlat=new OpenLayers.LonLat(feature.geometry.x,feature.geometry.y)
var OpenLayersPixel=feature.layer.map.getPixelFromLonLat(lonlat);var posMap=Ext.get(this.map.div).parent().getXY();var pos={};pos.left=parseInt(OpenLayersPixel.x+posMap[0],10)-Math.round(this.iconSize['default'].w/2);pos.top=parseInt(OpenLayersPixel.y+posMap[1],10)-Math.round(this.iconSize['default'].h/2);return pos;}
else{return null;}},destroy:function(){if(this.map&&this.map.events){this.map.events.unregister('move',this,this.move);}
this.map=null;this.layer=null;this.popuppedFeature=null;this.feature=null;Ext.destroy(this.popupDiv);this.popupDiv=null;Ext.get(this.popoverDiv).un('click',this.onPopoverClick,this);Ext.destroy(this.popoverDiv);this.popoverDiv=null;this.attributes=null;this.templates=null;this.clusterZoom=null;this.iconSize=null;},CLASS_NAME:"Geozet.Popup"});Geozet.Search=OpenLayers.Class({config:null,gazetteerUrl:null,searchFormId:null,initialize:function(config,map){this.config=config;this.map=map;this.gazetteerUrl=this.config['gazetteer'].url;this.gazetteerParam=this.config['gazetteer'].param;Ext.get('geozetContent').on('submit',this.onSubmit,this,{delegate:'form'});$('#geozetEnhancedSearch, #geozetCoreEntree').delegate('input','keydown',function(evt){evt.stopPropagation();});$('#geozetEnhancedSearch, #geozetCoreEntree').delegate('li/a','click',function(){var hash=$("span.hash",this).text();var x=$("span.x",this).text();var y=$("span.y",this).text();var z=$("span.z",this).text();if(x&&y){map.setCenter(new OpenLayers.LonLat(x,y),z);$('#geozetStart').remove();document.location.hash=hash;}
else{alert("fout met coordinaten");}
return false;});},setSearchForm:function(elementId){this.searchFormId=elementId;},onSubmit:function(evt,elm){this.search(elm.id||evt.target.id);evt.stopEvent();return false;},search:function(source,searchString){this.setSearchForm(source);$('.geozetError, .geozetSuggestions').remove();if(!searchString){searchString=$('#'+this.searchFormId+' input:first').val();}
else{var urlItems=Geozet.config.urlitems;var hashItems=searchString.split('/');searchString='';for(var i=0;i<urlItems.length;i++){var index=$.inArray(urlItems[i],hashItems);if(index>=0){searchString+=(hashItems[index+1]+' ');}}}
var searchTitle=$('#'+source+" input:first").attr('title');if(!searchString||searchString.length<3||searchString==searchTitle){this.showError(OpenLayers.i18n("shortSearchString"));}
else{this.sendRequest(searchString);}
return false;},showError:function(msg){$('#'+this.searchFormId).prepend('<p class="geozetError">'+msg+'</p>');},sendRequest:function(searchString,handleResponse){var params={request:'geocode'};params[this.gazetteerParam]=searchString;if(searchString&&searchString.length>0){OpenLayers.Request.GET({url:this.gazetteerUrl,params:params,scope:this,success:(handleResponse)?handleResponse:this.handleResponse,failure:this.handleError});}
return false;},sendRequestFromHash:function(hashAddressString,handleResponse){var addressWords=hashAddressString.split('/');var address={};address.street={}
address.street=this.findUrlHashValue(addressWords,"straat");address.building={number:this.findUrlHashValue(addressWords,"huisnummer"),subdivision:this.findUrlHashValue(addressWords,"toevoeging")};address.place={};address.place.CountrySubdivision=this.findUrlHashValue(addressWords,"provincie");address.place.CountrySecondarySubdivision=null;address.place.Municipality=this.findUrlHashValue(addressWords,"gemeente");address.place.MunicipalitySubdivision=this.findUrlHashValue(addressWords,"plaats")
address.postalCode=this.findUrlHashValue(addressWords,"postcode");var xlsAddress=new Geozet.Format.XLSAddress("NL",address);var xlslusFormat=new Geozet.Format.XLSLUS();var requestBody=xlslusFormat.writeGeocodeRequest(xlsAddress);OpenLayers.Request.POST({url:this.gazetteerUrl,data:requestBody,scope:this,success:(handleResponse)?handleResponse:this.handleResponse,failure:this.handleError});return false;},findUrlHashValue:function(thisArray,keyToFind){var i=thisArray.indexOf(keyToFind);if(i>=0&&(i+1)<thisArray.length){return thisArray[i+1];}
else{return"";}},handleResponse:function(req,returnCoords){$('.geozetError, .geozetSuggestions').remove();var responseText=req.responseText;if(responseText&&(responseText.indexOf('FAILED')!=-1||responseText.indexOf('Exception')!=-1||responseText.indexOf('No more credits')!=-1)){return false;}
var xlslusFormat=new Geozet.Format.XLSLUS();var xlslus=xlslusFormat.read(req.responseXML||req.responseText);var hits=xlslus[0].numberOfGeocodedAddresses;if(hits==0){this.showError(OpenLayers.i18n("noLocationFound"));}
else{if(hits>1){$('#'+this.searchFormId+' p.button').before('<h3 class="geozetSuggestions">'+OpenLayers.i18n("suggestionsTitle")+'</h3><ul class="geozetSuggestions"></ul>');}
for(i=0;i<hits;i++){var suggestion='';var geom=xlslus[0].features[i].geometry;var address=xlslus[0].features[i].attributes.address;var plaats=address.place.MunicipalitySubdivision;var gemeente=address.place.Municipality;var prov=address.place.CountrySubdivision;var adres='';var postcode='';var hash="";var zoom=null;if(address.street&&address.street.length>0){adres=address.street+' - ';hash+="/straat/"+encodeURIComponent(address.street);if(address.building){var toevoeging='';if(address.building.subdivision){toevoeging=address.building.subdivision}
adres+=address.building.number+toevoeging+' - ';hash+="/huisnummer/"+encodeURIComponent(address.building.number);hash+="/toevoeging/"+encodeURIComponent(toevoeging);}
if(!zoom){zoom='adres'}}
if(address.postalCode){adres+=address.postalCode+' - ';hash="/postcode/"+encodeURIComponent(address.postalCode)+hash;if(!zoom){zoom='postcode'}}
if(plaats){suggestion=adres+plaats+' (plaats)';if(!zoom){zoom='plaats'}}
else if(gemeente){suggestion=adres+gemeente+' (gemeente)';if(!zoom){zoom='gemeente'}}
else if(prov){suggestion=prov+' (provincie)';if(!zoom){zoom='provincie'}}
if(!zoom){zoom='standaard'}
if(plaats){hash="/plaats/"+encodeURIComponent(plaats)+hash;}
if(gemeente){hash="/gemeente/"+encodeURIComponent(gemeente)+hash;}
if(prov){hash="/provincie/"+encodeURIComponent(prov)+hash;}
if(hits>1){var x=geom?geom.x:150000;var y=geom?geom.y:450000;var z=geom?this.config.zoomScale[zoom]:this.config.zoomScale['provincie'];$("ul.geozetSuggestions").append('<li><a href="#">'+suggestion+' <span class="hash">'+hash+'</span>'+' <span class="x">'+x+'</span> <span class="y">'+y+'</span> <span class="z">'+z+'</span></a></li>');var height=Math.max(Ext.get('geozetAside').getHeight(),Ext.get('geozetArticle').getHeight());Ext.get('geozetContent').setHeight(height);}
else{var x=geom?geom.x:150000;var y=geom?geom.y:450000;var z=geom?this.config.zoomScale[zoom]:this.config.zoomScale['provincie'];if(returnCoords===true){return{center:new OpenLayers.LonLat(x,y),zoom:z};}
else
{this.map.setCenter(new OpenLayers.LonLat(x,y),z);$('#geozetStart').remove();document.location.hash=hash;}}}
$("ul.geozetSuggestions").show();}
return false;},handleError:function(req){return false;},destroy:function(){this.searchFormId=null;Ext.get('geozetContent').un('submit',this.onSubmit,this,{delegate:'form'});this.map=null;this.config=null;this.gazetteerUrl=null;},CLASS_NAME:"Geozet.Search"});Geozet.Strategy.Cluster=OpenLayers.Class(OpenLayers.Strategy.Cluster,{attributeName:null,attributeValue:null,initialize:function(options){OpenLayers.Strategy.Cluster.prototype.initialize.apply(this,[options]);},cluster:function(event){OpenLayers.Strategy.Cluster.prototype.cluster.apply(this,[event]);var features=this.layer.features;if(Geozet.Viewer.getLegend()){var state=Geozet.Viewer.getLegend().getState();for(var key in state){this.onUpdateThemeVisibility(key,state[key]);}}},addToCluster:function(cluster,feature){cluster.cluster.push(feature);if(feature.style==null||feature.style.display!="none"){cluster.attributes.count+=1;}},createCluster:function(feature){var cluster=OpenLayers.Strategy.Cluster.prototype.createCluster.apply(this,[feature]);var attributes={};attributes[this.attributeName]=this.attributeValue;OpenLayers.Util.extend(cluster.attributes,attributes);return cluster;},onUpdateThemeVisibility:function(cls,visible){for(var i=0,len=this.layer.features.length;i<len;i++){var feature=this.layer.features[i];var cssClass=null;var attributes=null;if(feature.cluster){var cnt=0;for(var j=0,lenj=feature.cluster.length;j<lenj;j++){var subFeature=feature.cluster[j];if(subFeature.attributes[this.attributeName]===cls){if(visible===false){if(subFeature.style==null){subFeature.style={};}
subFeature.style.display="none";}else{cssClass=subFeature.attributes[this.attributeName];attributes=subFeature.attributes;cnt++;delete subFeature.style;}}else if(subFeature.style==null||subFeature.style.display!="none"){cssClass=subFeature.attributes[this.attributeName];attributes=subFeature.attributes;cnt++;}}
if(cnt!==feature.attributes.count){feature.attributes.count=cnt;if(cnt===1){feature.attributes=OpenLayers.Util.applyDefaults(feature.attributes,attributes);feature.attributes[this.attributeName]=cssClass;}else{feature.attributes[this.attributeName]=this.attributeValue;}
if(cnt===0){if(feature.style==null){feature.style={};}
feature.style.display="none";}else if(feature.style){delete feature.style;}
feature.layer.drawFeature(feature);}}else{if(visible===false&&feature.attributes[this.attributeName]===cls){if(!feature.style){feature.style={};}
feature.style.display="none";feature.layer.drawFeature(feature);}else if(feature.style&&visible===true&&feature.attributes[this.attributeName]===cls){delete feature.style;feature.layer.drawFeature(feature);}}}},CLASS_NAME:'Geozet.Strategy.Cluster'});Geozet.plugins.ResizeMap=Ext.extend(Ext.util.Observable,{mapPanel:null,autoHeight:null,autoWidth:null,staticSize:null,isMaximized:null,scroll:42,constructor:function(config){Ext.apply(this,config);},init:function(mapPanel){this.mapPanel=mapPanel;this.mapPanel.on('afterrender',this.addAnchor,this);},destroy:function(){this.mapPanel.un('afterrender',this.addAnchor,this);this.mapPanel=null;this.anchor.un('click',this.toggleResizeMap,this);this.anchor.update('');Ext.destroy(this.anchor);this.anchor=null;Ext.EventManager.un(window,"resize",this.resizeMapOnBrowserResize,this);Ext.EventManager.un(window,"resize",this.toggleAnchor,this);this.purgeListeners();},addAnchor:function(){this.anchor=Ext.get(Ext.DomHelper.append(this.mapPanel.body,{tag:'a',href:'#',title:OpenLayers.i18n('resizeToggleTitle'),id:'toggleMapSize'}));this.anchor.on('click',this.toggleResizeMap,this);var parent=this.mapPanel.el.parent();var maxSize=this.getMaxAvailableSize();if(this.autoWidth===true){Ext.getBody().addClass('geozetMax');this.anchor.toggleClass('max');this.isMaximized=true;var w=Math.max(maxSize[0],this.staticSize[0]);parent.setWidth(w+parent.getBorderWidth("lr"));this.mapPanel.body.setWidth(w);var height=Math.max(Ext.get('geozetAside').getHeight(),Ext.get('geozetArticle').getHeight());Ext.get('geozetContent').setHeight(height);Ext.EventManager.on(window,"resize",this.resizeMapOnBrowserResize,this,{buffer:100});}
if(this.autoHeight===true){var h=Math.max(maxSize[1],this.staticSize[1]);parent.setHeight(h+parent.getBorderWidth("bt"));this.mapPanel.body.setHeight(h);}
this.mapPanel.map.updateSize();this.toggleAnchor();Ext.EventManager.on(window,"resize",this.toggleAnchor,this,{buffer:100});},toggleAnchor:function(){if(this.hidden===true||this.getMaxAvailableSize()[0]<this.staticSize[0]+this.anchor.getWidth()){this.anchor.hide();}else{this.anchor.show();}},getMaxAvailableSize:function(){var size=Ext.getBody().getViewSize();var pos=Ext.get(this.mapPanel.el).getXY();var offset=0;if(Ext.get(Geozet.config.attributionDiv)){offset=Ext.get(Geozet.config.attributionDiv).getHeight();}
return[(size.width-pos[0]-this.scroll),(size.height-pos[1]-this.scroll-offset)];},resizeMapOnBrowserResize:function(){this.resizeMap(false,false);},resizeMap:function(static,toggle){var w,h;var parent=this.mapPanel.el.parent();var maxSize=this.getMaxAvailableSize();if(static!==true){w=Math.max(maxSize[0],this.staticSize[0]);h=this.mapPanel.body.getHeight();}else{w=this.staticSize[0];if(this.autoHeight===true){h=Math.max(maxSize[1],this.staticSize[1]);}else{h=this.staticSize[1];}}
if(toggle===true){Ext.getBody().toggleClass('geozetMax');}
parent.setSize(w+parent.getBorderWidth("lr"),h+parent.getBorderWidth("bt"));this.mapPanel.body.setSize(w,h);this.mapPanel.map.updateSize();},toggleResizeMap:function(evt){this.anchor.toggleClass('max');if(this.isMaximized===true){if(this.autoHeight!==true){Ext.EventManager.un(window,"resize",this.resizeMapOnBrowserResize,this);Ext.get('geozetContent').dom.removeAttribute("style");}
this.isMaximized=false;this.resizeMap(true,true);}else{this.isMaximized=true;var height=Math.max(Ext.get('geozetAside').getHeight(),Ext.get('geozetArticle').getHeight());Ext.get('geozetContent').setHeight(height);this.resizeMap(false,true);Ext.EventManager.on(window,"resize",this.resizeMapOnBrowserResize,this,{buffer:100});}
evt.stopEvent();}});Geozet.Strategy.ServerSideCluster=OpenLayers.Class(OpenLayers.Strategy,{attribute:null,prefix:null,initialize:function(options){OpenLayers.Strategy.prototype.initialize.apply(this,[options]);},activate:function(){this.layer.events.on({"beforefeaturesadded":this.updateVisibility,scope:this});},deactivate:function(){this.layer.events.un({"beforefeaturesadded":this.updateVisibility,scope:this});},getFilterState:function(){if(Geozet.Viewer.getLegend()){return Geozet.Viewer.getLegend().getState();}},updateVisibility:function(evt){var features=evt.features;var state=this.getFilterState();for(var key in state){this.onUpdateThemeVisibility(key,state[key],features,true,true);}},onUpdateThemeVisibility:function(cls,visible,features,noDraw,subtractOnly){var featureCollection=features||this.layer.features;for(var i=0,len=featureCollection.length;i<len;i++){var feature=featureCollection[i];var cnt=parseInt(feature.attributes[this.attribute]);if(feature.attributes[this.prefix+'_'+cls]){var difference=parseInt(feature.attributes[this.prefix+'_'+cls]);if(visible===true){if(subtractOnly!==true){cnt+=difference;}}else{cnt-=difference;}
if(!feature.style&&cnt===0){feature.style={display:'none'};}else if(feature.style){delete feature.style;}
feature.attributes[this.attribute]=cnt;if(noDraw!==true){feature.layer.drawFeature(feature);}}}},CLASS_NAME:'Geozet.Strategy.ServerSideCluster'});Geozet.Vlakgericht=OpenLayers.Class({ITEMSPERPAGE:5,pageCurrent:1,pageLength:1,map:null,initialize:function(options){OpenLayers.Util.extend(this,options);var me=this;$('body').delegate('#geozetAlert','click',function(){me.geozetAlertClick(me.map);return false;});$('body').delegate('#geozetStartForward','click',function(){me.go(true);return false;});$('body').delegate('#geozetStartBack','click',function(){me.go(false);return false;});},go:function(next){var to=next?this.pageCurrent+1:this.pageCurrent-1;if((to>0)&&(to<=this.pageLength)){for(var i=1;i<=this.ITEMSPERPAGE;i++){$('#geozetFlatList li:nth-child('+(this.ITEMSPERPAGE*(this.pageCurrent-1)+i)+')').removeClass('active');$('#geozetFlatList li:nth-child('+(this.ITEMSPERPAGE*(to-1)+i)+')').addClass('active');}
this.pageCurrent=to;$('#geozetStart p.btn span').html(this.pageCurrent);$('#geozetStart p.btn a').removeClass().attr('disabled','');if(this.pageCurrent==this.pageLength){$('#geozetStartForward').addClass('inactive').attr('disabled','disabled');}
if(this.pageCurrent==1){$('#geozetStartBack').addClass('inactive').attr('disabled','disabled');}}
return false;},geozetAlertClick:function(map){var popup=Geozet.Viewer.getPopup();if(popup){popup.hidePopover();}
if($("#geozetPopup").html().length>0){$("#geozetPopup").hide();}
if($('#geozetContent.start').length!==0){$('#geozetMap').append('<div id="geozetStart"><div class="geozetStart"><a href="#" class="geozetClose" title="'+OpenLayers.i18n("geozetStartCloseTitle")+'">'+OpenLayers.i18n("geozetStartCloseText")+'</a><'+'h3 class="title-main">'+OpenLayers.i18n("vlakgerichtIntroTitle")+'</h3>'+'<p>'+OpenLayers.i18n("vlakgerichtIntroText")+'</p>'+'<h3 id="vlakkentitle" class="title-main">'+OpenLayers.i18n("vlakgerichtBusyText")+'<img src="static/css/img/loading.gif"/></h3>'+'</div>');$('a.geozetClose').focus();var bbox=null;var extent=map.getExtent();if(extent){bbox=extent.toBBOX();}
if(bbox!==null){OpenLayers.Request.GET({url:Geozet.config.vlakgerichteBekendmakingenService,params:{format:'json',bbox:bbox},scope:this,success:this.handleResponse,failure:this.handleError});}}
if(Ext.isIE6){Ext.get('geozetStart').setHeight(Ext.get('geozetMap').getHeight());}
return false;},handleResponse:function(req){var response=eval('('+req.responseText+')');if(response.vlakken){var vlakken=response.vlakken;var vlakkentitle=Geozet.config.templates['vlakgerichtTitle'].applyTemplate(vlakken);var vlakkenhtml="";for(var i=0;i<vlakken.length;i++){vlakken[i].activeClass=(i<this.ITEMSPERPAGE)?'active':'';vlakkenhtml+=Geozet.config.templates['vlakgerichtItem'].applyTemplate(vlakken[i]);}
if(vlakken.length>0){this.pageCurrent=1;this.pageLength=Math.ceil(vlakken.length/this.ITEMSPERPAGE);$('#vlakkentitle').html(vlakkentitle).after('<ul id="geozetFlatList"></ul>');$('#geozetFlatList').append(vlakkenhtml);$('div .geozetStart').append(Geozet.config.templates['vlakgerichtFooter'].applyTemplate({pageLength:this.pageLength}));}else{$('#vlakkentitle').html(OpenLayers.i18n("vlakgerichtNoResults"));this.pageLength=1;}}
else{}
return false;},handleError:function(req){$('#vlakkentitle').html(OpenLayers.i18n("vlakgerichtError"));this.pageLength=1;return false;},destroy:function(){this.map=null;},CLASS_NAME:"Geozet.Vlakgericht"});Geozet.Format.XLSAddress=OpenLayers.Class({addressee:null,countryCode:null,freeFormAddress:null,street:null,building:null,place:null,postalCode:null,initialize:function(countryCode,options){this.street=[];this.place={CountrySubdivision:null,CountrySecondarySubdivision:null,Municipality:null,MunicipalitySubdivision:null};OpenLayers.Util.extend(this,options);this.countryCode=countryCode;},format:function(){if(this.freeFormAddress){return this.freeFormAddress;}else{return this.getStreetText()+' '+this.getBuildingText()
+' '+this.getPostalCodeText()+' '+this.getPlaceText();}},getStreetText:function(address){if(!address){address=this;}
var text='';for(var si=0;si<address.street.length;si++){if(text!=''){text+=' ';}
text+=address.formatObject(address.street[si],Geozet.Format.XLSAddress.formattedStreetProperties);}
return text;},getBuildingText:function(address){if(!address){address=this;}
return address.formatObject(address.building,Geozet.Format.XLSAddress.formattedBuildingProperties);},getPostalCodeText:function(address){if(!address){address=this;}
return!address.postalCode?'':address.postalCode;},getPlaceText:function(address){if(!address){address=this;}
return address.formatObject(address.place,Geozet.Format.XLSAddress.formattedPlaceProperties);},formatObject:function(obj,props){if(!obj){return''};var text='';if(typeof obj=='string'){text=obj;}else if(props instanceof Array){for(var pi=0;pi<props.length;pi++){if(obj[props[pi]]){if(text!=''){text+=' ';}
text+=obj[props[pi]];}}}
return text;},CLASS_NAME:"Geozet.Format.XLSAddress"});Geozet.Format.XLSAddress.formattedPlaceProperties=['Municipality','MunicipalitySubdivision','CountrySecondarySubdivision','CountrySubdivision'];Geozet.Format.XLSAddress.formattedStreetProperties=['directionalPrefix','typePrefix','officialName','typeSuffix','directionalSuffix','muniOctant'];Geozet.Format.XLSAddress.formattedBuildingProperties=['number','subdivision','buildingName'];Geozet.Format.XLSLUS.v1=OpenLayers.Class(OpenLayers.Format.GML,{namespaces:{xls:"http://www.opengis.net/xls",gml:"http://www.opengis.net/gml",xsi:"http://www.w3.org/2001/XMLSchema-instance"},defaultPrefix:"xls",schemaLocation:null,addressClass:Geozet.Format.XLSAddress,srsName:'EPSG:4326',initialize:function(options){OpenLayers.Format.GML.prototype.initialize.apply(this,[options]);},read:function(data){var xlslus=[];this.readChildNodes(data,xlslus);return xlslus;},readers:{"xls":{"GeocodeResponse":function(node,xlslus){this.readChildNodes(node,xlslus);},"GeocodeResponseList":function(node,xlslus){var responseList={};responseList.features=[];responseList.numberOfGeocodedAddresses=node.getAttribute("numberOfGeocodedAddresses");this.readChildNodes(node,responseList);xlslus.push(responseList);},"GeocodedAddress":function(node,responseList){var feature=new OpenLayers.Feature.Vector();this.readChildNodes(node,feature);responseList.features.push(feature);},"GeocodeMatchCode":function(node,feature){var matchCode={};matchCode.accuracy=node.getAttribute("accuracy");matchCode.matchType=node.getAttribute("matchType");feature.attributes.geocodeMatchCode=matchCode;},"ReverseGeocodeResponse":function(node,xlslus){this.readChildNodes(node,xlslus);},"ReverseGeocodedLocation":function(node,xlslus){var feature=new OpenLayers.Feature.Vector();this.readChildNodes(node,feature);xlslus.push(feature);},"SearchCentreDistance":function(node,feature){var distance={};distance.value=node.getAttribute("value");distance.accuracy=node.getAttribute("accuracy");distance.uom=node.getAttribute("uom");if(!distance.uom){distance.uom="M";}
feature.attributes.searchCentreDistance=distance;},"Address":function(node,feature){var countryCode=node.getAttribute("countryCode");var address=new this.addressClass(countryCode);address.addressee=node.getAttribute("addressee");this.readChildNodes(node,address);feature.attributes.address=address;},"freeFormAddress":function(node,address){address.freeFormAddress=this.getChildValue(node);},"StreetAddress":function(node,address){this.readChildNodes(node,address);},"Building":function(node,address){var building={};building.number=node.getAttribute("number");building.subdivision=node.getAttribute("subdivision");building.buildingName=node.getAttribute("buildingName");address.building=building;},"Street":function(node,address){var street={};street.name=this.getChildValue(node);street.directionalPrefix=node.getAttribute("directionalPrefix");street.typePrefix=node.getAttribute("typePrefix");street.officialName=node.getAttribute("officialName");street.typeSuffix=node.getAttribute("typeSuffix");street.directionalSuffix=node.getAttribute("directionalSuffix");street.muniOctant=node.getAttribute("muniOctant");if(!street.directionalPrefix&&!street.typePrefix&&!street.officialName&&!street.typeSuffix&&!street.directionalSuffix&&!street.muniOctant){street=street.name;}
address.street.push(street);},"Place":function(node,address){var type=node.getAttribute("type");address.place[type]=this.getChildValue(node);},"PostalCode":function(node,address){address.postalCode=this.getChildValue(node);}},"gml":{"Point":function(node,feature){var parser=this.parseGeometry["point"];var geometry=parser.apply(this,[node]);if(this.internalProjection&&this.externalProjection){geometry.transform(this.externalProjection,this.internalProjection);}
feature.geometry=geometry;}}},writeGeocodeRequest:function(address){return this.writers.xls.GeocodeRequest.apply(this,[address]);},writeReverseGeocodeRequest:function(position){return this.writers.xls.ReverseGeocodeRequest.apply(this,[position]);},writers:{"xls":{"GeocodeRequest":function(address){var root=this.createElementNSPlus("GeocodeRequest",{attributes:{"xsi:schemaLocation":this.schemaLocation}});if(!(address instanceof Array)){address=[address];}
for(var i=0;i<address.length;i++){this.writeNode(root,"Address",address[i]);}
return root;},"ReverseGeocodeRequest":function(position){var root=this.createElementNSPlus("ReverseGeocodeRequest",{attributes:{"xsi:schemaLocation":this.schemaLocation}});this.writeNode(root,"Position",position);return root;},"Address":function(address){var node=this.createElementNSPlus("Address",{attributes:{"countryCode":address.countryCode,"addressee":address.addressee}});if(address.freeFormAddress){this.writeNode(node,"freeFormAddess",address.freeFormAddress);}else{this.writeNode(node,"StreetAddress",address);if(address.place){var classification=Geozet.Format.XLSLUS.v1.NamedPlaceClassification;for(var i=0;i<classification.length;i++){if(address.place[classification[i]]){var placeNode=this.writeNode(node,"Place",address.place[classification[i]]);this.setAttributes(placeNode,{"type":classification[i]});}}}
if(address.postalCode){this.writeNode(node,"PostalCode",address.postalCode);}}
return node;},"freeFormAddress":function(freeFormAddress){return this.createElementNSPlus("freeFormAddress",{value:freeFormAddress});},"StreetAddress":function(address){var node=this.createElementNSPlus("StreetAddress",{});if(address.building){this.writeNode(node,"Building",address.building);}
var street=address.street;if(!(street instanceof Array)){street=[street];}
for(var i=0;i<street.length;i++){this.writeNode(node,"Street",street[i]);}
return node;},"Building":function(building){return this.createElementNSPlus("Building",{attributes:{"number":building.number,"subdivision":building.subdivision,"buildingName":building.buildingName}});},"Street":function(street){if(typeof street=='string'){return this.createElementNSPlus("Street",{value:street});}else if(street&&street.name){return this.createElementNSPlus("Street",{value:street.name});}else{return this.createElementNSPlus("Street",{attributes:{"directionalPrefix":street.directionalPrefix,"typePrefix":street.typePrefix,"officialName":street.officialName,"typeSuffix":street.typeSuffix,"directionalSuffix":street.directionalSuffix,"muniOctant":street.muniOctant}});}},"Place":function(place){return this.createElementNSPlus("Place",{value:place});},"PostalCode":function(postalCode){return this.createElementNSPlus("PostalCode",{value:postalCode});},"Position":function(position){var node=this.createElementNSPlus("Position",{attributes:{"levelOfConf":position.levelOfConf}});if(position.CLASS_NAME&&position.CLASS_NAME=="OpenLayers.Geometry.Point"){position={point:position};}
this.writeNode(node,"gml:Point",position.point);if(position.shape){if(position.shape.CLASS_NAME&&position.shape.CLASS_NAME=="OpenLayers.Geometry.Polygon"){this.writeNode(node,"gml:Polygon",position.shape);}else if(position.shape.CLASS_NAME&&position.shape.CLASS_NAME=="OpenLayers.Geometry.MultiPolygon"){this.writeNode(node,"gml:MultiPolygon",position.shape);}}
if(position.qop){}
if(position.time){}
if(position.speed){}
if(position.direction){}
return node;}},"gml":{"Point":function(point){var node=this.createElementNSPlus("gml:Point",{attributes:{srsName:this.srsName}});this.writeNode(node,"gml:pos",point);return node;},"pos":function(point){return this.createElementNSPlus("gml:pos",{value:point.x+' '+point.y});},"CircleByCenterPoint":function(geometry){},"Polygon":function(geometry){return this.buildGeometryNode(geometry);},"MultiPolygon":function(geometry){return this.buildGeometryNode(geometry);}}},getNamespacePrefix:function(uri){var prefix=null;if(uri==null){prefix=this.namespaces[this.defaultPrefix];}else{var gotPrefix=false;for(prefix in this.namespaces){if(this.namespaces[prefix]==uri){gotPrefix=true;break;}}
if(!gotPrefix){prefix=null;}}
return prefix;},readChildNodes:function(node,obj){var children=node.childNodes;var child,group,reader,prefix,local;for(var i=0;i<children.length;++i){child=children[i];if(child.nodeType==1){prefix=this.getNamespacePrefix(child.namespaceURI);local=child.nodeName.split(":").pop();group=this.readers[prefix];if(group){reader=group[local];if(reader){reader.apply(this,[child,obj]);}}}}},writeNode:function(parent,name,obj){var prefix,local;var split=name.indexOf(":");if(split>0){prefix=name.substring(0,split);local=name.substring(split+1);}else{prefix=this.getNamespacePrefix(parent.namespaceURI);local=name;}
var child=this.writers[prefix][local].apply(this,[obj]);parent.appendChild(child);return child;},createElementNSPlus:function(name,options){options=options||{};var loc=name.indexOf(":");var uri=options.uri||this.namespaces[options.prefix];if(!uri){loc=name.indexOf(":");uri=this.namespaces[name.substring(0,loc)];}
if(!uri){uri=this.namespaces[this.defaultPrefix];}
var node=this.createElementNS(uri,name);if(options.attributes){this.setAttributes(node,options.attributes);}
if(options.value){node.appendChild(this.createTextNode(options.value));}
return node;},setAttributes:function(node,obj){var value,loc,alias,uri;for(var name in obj){if(obj[name]){value=obj[name].toString();uri=this.namespaces[name.substring(0,name.indexOf(":"))]||null;this.setAttributeNS(node,uri,name,value);}}},CLASS_NAME:"Geozet.Format.XLSLUS.v1"});Geozet.Format.XLSLUS.v1.NamedPlaceClassification=["CountrySubdivision","CountrySecondarySubdivision","Municipality","MunicipalitySubdivision"];Geozet.Legend=Ext.extend(Ext.BoxComponent,{visibleClasses:null,map:null,ulCls:null,onRender:function(){Geozet.Legend.superclass.onRender.apply(this,arguments);Ext.get(this.container).on('click',this.handleClick,this,{delegate:'input'});this.header=Ext.DomHelper.append(this.container,{tag:'h3'});var html='<span>'+OpenLayers.i18n("legendTitle")+'</span><a class="geozetInfo" href="#">info</a>';Ext.get(this.header).update(html);var info=Ext.DomHelper.append(this.container,{tag:'p','class':'geozetInfo'});Ext.get(info).update(OpenLayers.i18n("legendInfoText"));var list=Ext.DomHelper.append(this.container,{tag:'ul','class':this.ulCls});for(var key in this.legendConfig){var filter=this.legendConfig[key];var item=Ext.DomHelper.append(list,{tag:"li","class":filter.displayClass});if(filter.showCheckbox===false){Ext.get(item).update(filter.label);}else{var elConfig={tag:"input","type":"checkbox",id:"geo-"+filter.displayClass};if(this.visibleClasses==null){elConfig.checked="checked";}else if(this.visibleClasses.indexOf(filter.displayClass)!==-1){elConfig.checked="checked";}
var cb=Ext.DomHelper.append(item,elConfig);var label=Ext.DomHelper.append(item,{tag:"label",html:filter.label,"for":"geo-"+filter.displayClass});}}},getState:function(){var state={};Ext.each(Ext.get(this.container).query('[type=checkbox]'),function(cb){var cls=cb.id.substring(4);state[cls]=cb.checked;});return state;},destroy:function(){Ext.get(this.container).un('click',this.handleClick,this,{delegate:'input'});Ext.destroy(this.container);this.container=null;Ext.destroy(this.header);this.header=null;this.map=null;Geozet.Legend.superclass.destroy.apply(this,arguments);},handleClick:function(evt){var target=Ext.get(evt.target);var cls=target.parent().dom.className;var visible=target.dom.checked;var popup=Geozet.Viewer.getPopup();if(popup){popup.hidePopup();}
for(var i=0,len=this.map.layers.length;i<len;i++){var layer=this.map.layers[i];if(layer instanceof OpenLayers.Layer.Vector){for(var j=0,lenj=layer.strategies.length;j<lenj;j++){var strategy=layer.strategies[j];if(strategy instanceof Geozet.Strategy.Cluster||strategy instanceof Geozet.Strategy.ServerSideCluster){strategy.onUpdateThemeVisibility(cls,visible,null,!layer.inRange);break;}}}}}});Geozet.Control.Click=OpenLayers.Class(OpenLayers.Control,{clickFunction:null,autoActivate:true,initialize:function(options){OpenLayers.Control.prototype.initialize.apply(this,arguments);this.handler=new OpenLayers.Handler.Click(this,{'click':this.clickFunction});},CLASS_NAME:"Geozet.Control.Click"});Geozet.Renderer.Anchor=OpenLayers.Class(OpenLayers.Renderer,{imgPath:null,iconSize:null,classificationInfo:null,initialize:function(containerID,options){OpenLayers.Renderer.prototype.initialize.apply(this,arguments);OpenLayers.Util.extend(this,options);this.root=this.container;},destroy:function(){this.clear();this.root=null;this.imgPath=null;this.iconSize=null;this.classificationInfo=null;OpenLayers.Renderer.prototype.destroy.apply(this,arguments);},drawFeature:function(feature,style){if(style==null){style=feature.style;}
if(feature.geometry){var bounds=feature.geometry.getBounds();if(bounds){if(!bounds.intersectsBounds(this.extent)){style={display:"none"};}
if(feature.cluster!==undefined){style.cluster=true;}
var popup=Geozet.Viewer.getPopup();var title=null;if(popup){title=popup.getTitleForFeature(feature);}
var rendered=this.drawGeometry(feature.geometry,style,feature.id,title);if(style.display!="none"&&style.label&&rendered!==false){this.drawText(feature.id,style,location);}else{this.removeText(feature.id);}
return rendered;}}},clear:function(){if(this.root){while(this.root.childNodes.length>0){this.root.removeChild(this.root.firstChild);}}},getFeatureIdFromEvent:function(evt){var target=evt.target;var useElement=target&&target.correspondingUseElement;var node=useElement?useElement:(target||evt.srcElement);var featureId=node._featureId;return featureId;},supported:function(){return true;},setExtent:function(extent,resolutionChanged){OpenLayers.Renderer.prototype.setExtent.apply(this,arguments);var resolution=this.getResolution();this.left=-extent.left/resolution;this.top=extent.top/resolution;return false;},drawText:function(featureId,style,location){var node=document.getElementById(featureId);if(node&&style.label!=="undefined"){if(node.children.length===1){var text=document.createElement('span');text._featureId=featureId;text.innerHTML=style.label;node.appendChild(text);}else if(node.children.length==2){node.children[1].innerHTML=style.label;}}},eraseGeometry:function(geometry,featureId){var element=document.getElementById(featureId);if(element&&element.parentNode){element.parentNode.removeChild(element);}},removeText:function(featureId){},getLength:function(label){var len=(""+label).length;if(len>5){len=5;}
return len;},appendImage:function(node,style){var extension=Ext.isIE6?"gif":"png";var baseName='';var cls='';if(style.cluster===true&&(style.label>1||style.serverside===true)){cls=baseName=style.cssClass+"-"+this.getLength(style.label);if(style.popupActive==="true"){cls+=' active';}}else{baseName=style.cssClass;if(style.popupActive==="true"){cls='active';}}
node.className=cls;var imgUrl=this.imgPath+baseName+"."+extension;var title=this.classificationInfo[style.cssClass].label;var icon=null;if(node.childNodes.length<1){icon=document.createElement('img');node.appendChild(icon);}else{icon=node.childNodes[0];}
icon.setAttribute("alt",title);icon.setAttribute("src",imgUrl);},getIconSize:function(style){var key;if(style.cluster===true&&style.label>1){key=style.cssClass+"-"+this.getLength(style.label);}else{key='default';}
return this.iconSize[key];},drawGeometry:function(geometry,style,featureId,title){var rendered=false;if(geometry instanceof OpenLayers.Geometry.Point){var iconSize=this.getIconSize(style);var node=document.getElementById(featureId);if(node){if(style.display!="none"){var resolution=this.getResolution();var x=Math.round((geometry.x/resolution+this.left)-iconSize.w/2);var y=Math.round((this.top-geometry.y/resolution)-iconSize.h/2);this.appendImage(node,style);node.style.left=x+"px";node.style.top=y+"px";rendered=true;}}else{if(style.display=="none"){return rendered;}else{node=document.createElement("a");node.setAttribute('title',title);node.setAttribute('href','#');node.id=featureId;this.appendImage(node,style);node._featureId=featureId;node.childNodes[0]._featureId=featureId;var resolution=this.getResolution();var x=Math.round((geometry.x/resolution+this.left)-iconSize.w/2);var y=Math.round((this.top-geometry.y/resolution)-iconSize.h/2);node.style.left=x+"px";node.style.top=y+"px";this.root.appendChild(node);rendered=true;}}
if(rendered==false){this.root.removeChild(node);}
return rendered;}},CLASS_NAME:"GeoZet.Renderer.Anchor"});Geozet.Format.XLSLUS.v1_1_0=OpenLayers.Class(Geozet.Format.XLSLUS.v1,{VERSION:"1.1.0",schemaLocation:"http://www.opengis.net/xls http://schemas.opengis.net/ols/1.1.0/LocationUtilityService.xsd",initialize:function(options){Geozet.Format.XLSLUS.v1.prototype.initialize.apply(this,[options]);},CLASS_NAME:"Geozet.Format.XLSLUS.v1_1_0"});